### ISSUE TITLE
Make the X more powerful

### ISSUE THREAD

**Issue by fuzihaofzh** [0101/pipetools#7]
Is it possible to suport more operations like:
```
['a', 'b', 'c'] > pipe | '\n'.join(X)
```

**Comment by 0101** [comment]
Hey, 

you'll have to expand that a bit - what do you propose would be the result of that operation?

You can already do:
```python
['a', 'b', 'c'] > pipe | '\n'.join
```
Which will produce `'a\nb\nc'`.

Maybe you need to provide a different example of the functionality you're missing.

**Comment by 0101** [comment]
No response, so I'm closing this now. Feel free to reopen with more details. 

(The X object most definitely _can_ be made more powerful ;))

**Comment by fuzihaofzh** [comment]
Thanks for your help. If I found some I will report it.
